// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationService.Context;

#nullable disable

namespace ReservationService.Migrations
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20260220222842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationService.Models.Reservation", b =>
                {
                    b.Property<Guid>("reservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("sessionId")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("reservationId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationService.Models.Session", b =>
                {
                    b.Property<Guid>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<int>("trainerId")
                        .HasColumnType("integer");

                    b.Property<int>("trainingType")
                        .HasColumnType("integer");

                    b.HasKey("sessionId");

                    b.ToTable("Sessions");

                    b.HasDiscriminator<string>("SessionType").HasValue("Session");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReservationService.Models.TrainingHall", b =>
                {
                    b.Property<Guid>("trainingHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("trainingHallName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("trainingHallId");

                    b.ToTable("TrainingHalls");
                });

            modelBuilder.Entity("ReservationService.Models.GroupSession", b =>
                {
                    b.HasBaseType("ReservationService.Models.Session");

                    b.Property<int>("hallId")
                        .HasColumnType("integer");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ReservationService.Models.PersonalSession", b =>
                {
                    b.HasBaseType("ReservationService.Models.Session");

                    b.HasDiscriminator().HasValue("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
