// <auto-generated />
using System;
using MeasurmentService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeasurmentService.Migrations
{
    [DbContext(typeof(MeasurementContext))]
    [Migration("20260219214826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeasurmentService.Models.Guideline", b =>
                {
                    b.Property<int>("GuidelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuidelineId"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("GuidelineId");

                    b.ToTable("Guidelines");
                });

            modelBuilder.Entity("MeasurmentService.Models.MeasurementAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("GuidelineId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId");

                    b.HasIndex("GuidelineId");

                    b.ToTable("MeasurementAppointments");
                });

            modelBuilder.Entity("MeasurmentService.Models.MeasurementAppointment", b =>
                {
                    b.HasOne("MeasurmentService.Models.Guideline", "Guideline")
                        .WithMany()
                        .HasForeignKey("GuidelineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("MeasurmentService.Models.Measurements", "Measurements", b1 =>
                        {
                            b1.Property<int>("MeasurementAppointmentAppointmentId")
                                .HasColumnType("integer");

                            b1.Property<double?>("BodyFatPercent")
                                .HasColumnType("double precision");

                            b1.Property<double?>("HeightCm")
                                .HasColumnType("double precision");

                            b1.Property<double?>("WeightKg")
                                .HasColumnType("double precision");

                            b1.HasKey("MeasurementAppointmentAppointmentId");

                            b1.ToTable("MeasurementAppointments");

                            b1.WithOwner()
                                .HasForeignKey("MeasurementAppointmentAppointmentId");
                        });

                    b.Navigation("Guideline");

                    b.Navigation("Measurements")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
