// <auto-generated />
using System;
using MeasurmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeasurmentService.Migrations
{
    [DbContext(typeof(MeasurementContext))]
    partial class MeasurementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeasurmentService.Models.Guideline", b =>
                {
                    b.Property<Guid>("GuidelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CreatedByNutritionistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("GuidelineId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Guidelines");
                });

            modelBuilder.Entity("MeasurmentService.Models.MeasurementAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentId");

                    b.ToTable("MeasurementAppointments");
                });

            modelBuilder.Entity("MeasurmentService.Models.Guideline", b =>
                {
                    b.HasOne("MeasurmentService.Models.MeasurementAppointment", "MeasurementAppointment")
                        .WithOne("Guideline")
                        .HasForeignKey("MeasurmentService.Models.Guideline", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementAppointment");
                });

            modelBuilder.Entity("MeasurmentService.Models.MeasurementAppointment", b =>
                {
                    b.OwnsOne("MeasurmentService.Models.Measurements", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("MeasurementAppointmentAppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("BodyFatPercent")
                                .HasColumnType("double precision");

                            b1.Property<double?>("HeightCm")
                                .HasColumnType("double precision");

                            b1.Property<double?>("WeightKg")
                                .HasColumnType("double precision");

                            b1.HasKey("MeasurementAppointmentAppointmentId");

                            b1.ToTable("MeasurementAppointments");

                            b1.WithOwner()
                                .HasForeignKey("MeasurementAppointmentAppointmentId");
                        });

                    b.Navigation("Measurements")
                        .IsRequired();
                });

            modelBuilder.Entity("MeasurmentService.Models.MeasurementAppointment", b =>
                {
                    b.Navigation("Guideline");
                });
#pragma warning restore 612, 618
        }
    }
}
